import type { Metadata } from "next";

import Grotesk from "@/libs/fonts";
import "./globals.css";
import SmoothScrolling from "@/libs/SmoothScrolling";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${Grotesk.className} antialiased h-full flex flex-col`}>
        <SmoothScrolling>{children}</SmoothScrolling>
      </body>
    </html>
  );
}
